env:
  browser: true
  es2021: true
  jest/globals: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
extends:
  - "react-app"
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:json/recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:jest/recommended"
settings:
  react:
    version: detect
plugins:
  - prettier
  - react
  - jsx
  - json
  - import
  - jest
  - "@typescript-eslint"
rules:
  no-console: "off"
  no-unused-vars: warn
  no-use-before-define: warn
  eqeqeq: warn
  func-names: "off"
  object-shorthand: "off"
  no-shadow: "off"
  spaced-comment:
    - 2
    - always
  consistent-return: "off"
  no-underscore-dangle: "off"
  no-param-reassign: error
  no-nested-ternary: "off"
  arrow-body-style: "off"
  prefer-arrow-callback: "off"
  dot-notation: "off"
  no-tabs: "off"
  react/prop-types: "off"
  # conflicting or may conflict with prettier-
  "@typescript-eslint/no-extra-semi": "off"
  dot-location: "off"
  new-parens: "off"
  no-mixed-spaces-and-tabs: "off"
  no-whitespace-before-property: "off"
  rest-spread-spacing: "off"
  unicode-bom: "off"
  no-mixed-operators: "off"
  no-unexpected-multiline: "off"
